ithewei/libhv

README.md, base/hmutex.h, base/hplatform.h, base/hsocket.c, base/hsocket.h, base/htime.c, base/htime.h, event/evport.c, event/hevent.c, event/hloop.c, event/iowatcher.h, event/nio.c, http/server/HttpServer.cpp, protocol/icmp.c, readme_cn.md
Changes:
* Fix conflicting declarations which prevent libhv from compiling successfully on Solaris.
* Add support for I/O multiplexing via Solaris' event ports.
Testing:
* Tested on latest Solaris 11.4.
* Built with gcc 7.3.0.
* Unit tests and examples work as expected.
=> Add support for Oracle Solaris

Makefile
`g++ -g -Wall -std=c++11 -o bin/asio_echo     echo-servers/asio_echo.cpp   -lboost_system
/usr/bin/ld: /tmp/ccm09l4M.o: in function `boost::asio::detail::posix_event::posix_event()':
/usr/include/boost/asio/detail/impl/posix_event.ipp:42: undefined reference to `pthread_condattr_setclock'
/usr/bin/ld: /tmp/ccm09l4M.o: in function `boost::asio::detail::posix_thread::~posix_thread()':
/usr/include/boost/asio/detail/impl/posix_thread.ipp:35: undefined reference to `pthread_detach'
/usr/bin/ld: /tmp/ccm09l4M.o: in function `boost::asio::detail::posix_thread::join()':
/usr/include/boost/asio/detail/impl/posix_thread.ipp:42: undefined reference to `pthread_join'
/usr/bin/ld: /tmp/ccm09l4M.o: in function `boost::asio::detail::posix_thread::start_thread(boost::asio::detail::posix_thread::func_base …
=> fix build asio_echo error.

event/hevent.h, event/hloop.c, event/hloop.h
1、强制转换了两个long乘数为 long long类型；
2、修改了htimeout_s的timeout精度为uint64_t（这样更方便些）
3、修改htimer_add函数的第三个参数类型为uint64_t。
2和3不是必须的，但建议将精度改成一致的，作者可以考虑下~
=> fix next_timeout overflow

ssl/openssl.c
如果不开启该模式，当调用SSL_write只能写入部分数据时，剩余数据会被复制到hv的队列。稍后再次调用SSL_write写数据时，openssl会检查这次写入操作的buffer地址是否跟上次未完成的写入操作的buffer地址一致，如果不一致就会返回错误，导致连接关闭。开启该模式后，openssl允许两次操作用不同的buffer，但调用者还是确保数据的一致性。详见openssl的文档说明：https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_mode.html
=> 设置openssl的'accept moving write buffer'模式

base/hmain.c, base/hmain.h
Hello!!!
Valgrind report memory leak. When main_ctx_init function is used, is it because are made 5 SAFE_ALLOC in lines 119/120/122/147 and 148. This patch add the main_ctx_finish function to allow to call and free resources in the end of main function.
=> [bug fix]: Valgrind report memory leak in main_ctx_init

base/hplatform.h
测试MT7628芯片（MIPS架构，OpenWrt操作系统）通过，增加MIPS架构定义，详见[issue](https://github.com/ithewei/libhv/issues/234)
=> add mips and mips64 arch define

event/hevent.c
当监听一个普通的fd，比如串口，如果设置了读超时，程序会崩溃
调用栈：hio_set_read_timeout -> __read_timeout_cb -> SOCKADDR_STR -> sockaddr_str
sockaddr_str内部 addr->sa，由于没有检查参数addr值是否为NULL，触发异常
=> crash when fd type is not socket and read/write timeout

Makefile
不开O3，这不是欺负c++么，实际开O3后，asio略占上风
libevent running on port 2001
libev running on port 2002
libuv running on port 2003
libhv running on port 2004
asio running on port 2005
poco running on port 2006
muduo running on port 2007
==============2001=====================================
Running 10s test @ 127.0.0.1:2001
2 threads and 100 connections, send 1024 bytes each time
total readcount=968263 readbytes=991501312
throughput = 94 MB/s
==============2002=====================================
Running 10s test @ 127.0.0.1:2002
2 threads and 100 connections, send 1024 bytes each time
total readcount=1649179 readbytes=1688759296
throughput = 161 MB/s
==============2003=====================================
Running 10s test @ 127.0.0.1:2003
2 threads and 100 connections, send 1024 bytes each time
total …
=> add -O3 for benchmark

base/hsocket.c
修复在 linux 平台，通过fork创建的子进程继承 libhv 占有的端口的问题
=> bugfix: fix for child processes that bind ports after fork() on Linux platforms

base/htime.c
修改cron_next_timeout在week参数大于等于0时，日期计算错误的问题
=> fix cron_next_timeout

http/client/HttpClient.cpp
Removed `fprintf` from `http/client/HttpClient.cpp` as it seems to be redudant here because of `hloge("connect %s:%d failed!", host, port);`
=> Removed redundant fprintf from HttpClient

ssl/mbedtls.c
`errno` should not be used on Windows.
`libhv` provides correct cross-platform `socket_errno()`, so it definitely should be used instead.
=> mbedtls fix for windows

evpp/EventLoopThread.h
Issue: when AsyncHttpClient is destructed at APP exiting time, the EventLoopThread status is freezing as Stopping. So the loop waiting the Stopped status can not exit. Solution: when stop the EventLoopThead, waiting the thread-object exit instead of waiting the Stopped status.
=> fixbug: EventLoopThread::stop cannot end when loop_thread is destroyed when app exited

http/wsdef.h
=> fix linux gcc4.8.5 warning:提领类型双关的指针将破坏强重叠规则

http/HttpMessage.cpp
#442 
尝试通过修改HttpMessage.cpp中的业务逻辑，将Header中的\r\n转义成\\r\\n，即可解决漏洞中描述的问题。
=> 修复解决 CVE-2023-26148

base/hlog.c, base/hlog.h
当前在带色彩日志输出时，换行符号 “\n” 在 CLR_CLR 之前；因此在输出“FATAL”级别那种红底白字日志时，会导致下一行背景同样为红色；影响美观。
=> fix colored log line break "\n" position

base/hsocket.h
在<https://github.com/the-tcpdump-group/libpcap/blob/master/pcap/socket.h>第70行
```c
/*!
* \brief In Winsock, a socket handle is of type SOCKET; in UN*X, it's
* a file descriptor, and therefore a signed integer.
* We define SOCKET to be a signed integer on UN*X, so that it can
* be used on both platforms.
*/
#ifndef SOCKET
#define SOCKET int
#endif
```
=> unix平台SOCKET与libpcap重定义

cpputil/singleton.h
**修改前**:instance()函数中使用的是双重校验锁,
**修改后**:instance()中使用std::call_once替换双重校验所,增加多线程下线程安全性
问题主要出在内存模型和可见性上。在多线程环境中，可能存在指令重排或内存可见性的问题。因此，在第一次检查和初始化之间，另一个线程可能会看到某个对象已经被分配内存但尚未被完全初始化的情况，这可能导致使用未完全初始化的对象，从而产生不确定的行为。
**例**:首先new一个对象时，分为三个步骤，1分配内存 2构造对象 3返回指针。所以常规顺序是123，但是编译器有时候为了优化会指令重排，导致顺序变成132，这里我们考虑这么一种情况
A线程：new1分配内存并按照指令重拍之后的顺序将2地址返回s_pInstance指针（这时候s_pInstance指针是非空的，但是还没有到达构造构造，此时时间片用完，线程切换）
B线程进入，此时发现s_pInstance是非空的，便直接将s_pInstance返回给调用者，而调用着使用这个没有构造的对象将会发生不可预测的后果
指令重拍原因很多，比如编译器优化或者cpu指令流水线导致
**修改前**:exitInstance() 函数原本使用mutex的lock()和unlock()
**修改后**:使用lock_guard替换mutex,避免delete之前存在异常,导致mutex锁无法正确释放
=> Increased multithreading security

cpputil/hstring.cpp
如果string为`url=http://127.0.0.1?token=12345&name=test`
方法`splitKV(string, ',', '=')`的分割结果不正确: `url=test`
=> 修复kv值切割bug

mqtt/mqtt_client.h
Without the change build on `gcc-13` fails as:
[ 98%] Built target hmain_test
In file included from /build/source/examples/mqtt/mqtt_client_test.cpp:10:
/build/source/examples/../mqtt/mqtt_client.h: In member function 'int hv::MqttClient::publish(const std::string&, const std::string&, int, int, MqttCallback)':
/build/source/examples/../mqtt/mqtt_client.h:232:25: error: invalid use of incomplete type 'const std::string' {aka 'const class std::__cxx11::basic_string<char>'}
232 |         msg.topic_len = topic.size();
|                         ^~~~~
=> mqtt_client.h: add missing `<string>` include for `gcc-13`

http/server/HttpHandler.cpp
fix header if-none-match misspell in the HttpHandler.cpp
=> httphandler.cpp: fix if-none-match header misspell (#492)

.bazelrc, .gitignore, BUILD.bazel, WORKSPACE.bazel, examples/BUILD.bazel
This pull request adds support for building libhv using the Bazel build system. Bazel offers several advantages over traditional build systems like Make and CMake, such as incremental builds and simpler usage.
- Added Bazel BUILD files for building libhv and its examples
- Created a demo project that demonstrates how to use libhv with Bazel (https://github.com/Edward-Elric233/libhv-bazel-test)
The current implementation provides basic support for building libhv with Bazel on Linux, but there are a few known limitations:
1. Header file paths: The current implementation requires users to include libhv headers without the hv/ prefix, which differs from the Make/CMake builds. This is due to a limitation in Bazel's cc_library rule, which requires internal and external header paths to be the …
=> Add Bazel Build Support for libhv

CMakeLists.txt
I have been considering manually packaging libhv into RPM and DEB packages for a while. Recently, due to work requirements, I learned about the [Infinity project](https://github.com/infiniflow/infinity) and discovered that CMake can directly use CPack for packaging. By adding just a few descriptive statements in the CMakeLists.txt file, RPM, DEB, and TGZ packages can be generated in the build directory by executing the `cpack` command. These packages can be placed in the Release section, allowing users to install and use libhv easily through their package manager, eliminating the need for manual compilation.
```bash
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .
$ cpack
$ ls libhv-*
libhv-1.0.0-x86_64.deb  libhv-1.0.0-x86_64.rpm  libhv-1.0.0-x86_64.tar.gz
```
Users can download the …
=> Add support for CPack, allowing easy creation of RPM and DEB packages

event/nio.c
=> fix:udp clients localaddr

mqtt/mqtt_client.c, mqtt/mqtt_client.h
add mqtt_client_set_host function, used by switch host when connected…
添加 mqtt_client_set_host  接口函数, 用于当连接断开的时候切换服务器.
=> 增加 mqtt_client_set_host  接口函数, 

CMakeLists.txt
在 `CMakeLists.txt` 中增加以下内容
```cmake
if (NOT HAVE_CLOCK_GETTIME)
include(CheckLibraryExists)
check_library_exists(rt clock_gettime "" HAVE_CLOCK_GETTIME_IN_RT)
if (HAVE_CLOCK_GETTIME_IN_RT)
set(HAVE_CLOCK_GETTIME ${HAVE_CLOCK_GETTIME_IN_RT})
endif()
endif()
```
1. **新增宏定义**：
在 `cmake/utils.cmake` 中新增宏 `project_check_library_function`，用于检查特定库中的函数是否存在。该宏的定义如下：
```cmake
macro(project_check_library_function library function local)
string(TOUPPER ${library} str1)
string(TOUPPER ${function} str2)
set(str3 HAVE_${str2}_IN_${str1})
check_library_exists("${library}" "${function}" "${local}" ${str3})
if (${str3})
set(${str3} 1)
else()
set(${str3} 0)
endif()
endmacro()
```
2. **更新 `CMakeLists.txt`**：
在 `CMakeLists.txt` 中使用新定义的宏来检查 `clock_gettime` 函数是否存在于 `rt` 库中：
```cmake …
```
=> 改进 CMake 中 clock_gettime 的兼容性检查

base/hatomic.h, base/hplatform.h, base/htime.c, event/hloop.c, ssl/wintls.c
- 添加 `__GNUC_PREREQ` 检查以支持原子操作（需要 GCC 4.1+）
- 在 `gettick_ms()` 中添加显式类型转换以修复整数溢出风险
- 消除未使用变量/函数的编译警告
---
- Add `__GNUC_PREREQ` check for atomic operations (requires GCC 4.1+)
- Fix integer overflow risk in `gettick_ms()` with explicit type casting
- Eliminate unused variable/function warnings
=> fix: improve compiler compatibility and warnings

base/hplatform.h, event/hloop.c
1. 解决直接make时MacOs系统编译错误
2. 消除riscv架构处理器编译警告
=> 解决Mac编译错误，消除riscv编译警告

http/http_parser.c
**Description**
This PR fixes a security vulnerability in http_parser_execute() that was cloned from node but did not receive the security patch. The original issue was reported and fixed under https://github.com/nodejs/node/commit/fc70ce08f5818a286fb5899a1bc3aff5965a745e.
This PR applies the same patch to eliminate the vulnerability.
**References**
https://nvd.nist.gov/vuln/detail/CVE-2020-8287
https://github.com/nodejs/node/commit/fc70ce08f5818a286fb5899a1bc3aff5965a745e
=> Fix: Potential Vulnerability in Cloned Function

cpputil/hdir.cpp, cpputil/hstring.cpp, cpputil/hstring.h, http/server/FileCache.cpp
Windows HTTP服务注意了 #559 合并之后的版本性能是有异常的，我也是最近压测无意中发现，分析源码排查老半天才发现原因在codecvt编码转换
修复Windows defaultStaticHandler性能错误
Windows版本从合并 #559 之后HTTP服务默认静态处理因编码转换严重影响服务性能。
为了方便解决Windows高性能宽字符函数编码转换，在hstring.h增加了hv::wchar_to_utf8和hv::utf8_to_wchar函数
顺便修复http服务遇到中文路径时stat不可用导致文件缓存逻辑故障 和 http服务目录索引中文乱码问题
=> 修复HTTP服务Windows性能异常和中文路径相关Bug

ssl/openssl.c
It was necessary to deploy http server with ssl, but the certificate that was used was a chain of certificates. Libhv read only the first one. Added the ability to read a chain of certificates
Before:
```
> openssl s_client -connect 10.23.18.4:9092
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C = US, ST = Florida, L = Jacksonville, O = SomeOrg, emailAddress = some@email.com, CN = thedomain.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = Florida, L = Jacksonville, O = SomeOrg, emailAddress = some@email.com, CN = thedomain.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = Florida, L = Jacksonville, O = SomeOrg, emailAddress = some@email.com, CN = thedomain.com
verify return:1 …
```
=> ADD : Read ssl certificate from chain file

CMakeLists.txt, base/hatomic.h, base/hbase.c, base/rbtree.h, evpp/EventLoop.h, evpp/TcpClient.h, http/server/HttpServer.cpp, http/websocket_parser.c, hv.rc.in
add cmake install windows debug pdb
fix known compilation warnings
https://github.com/ithewei/libhv/issues/663
=> add windows dll versions resource

base/hmain.c
Windows环境-s=stop信号无条件TerminateProcess会导致hmain.c内部以及用户业务层设置的atexit完全失效，所以解除了被注释的TermEvent处理方式，并且增加了等待结束触发信号只有2s超时才执行TerminateProcess强制结束，反之则只会触发正常的exit->atexit回调。
=> support windows stop signal atexit callback

http/server/HttpServer.cpp
```c
for (int idx = 0; ; ++idx) {
loop = m_server.loop(idx);
if (!loop) break;
....
}
```
类似上述迭代获取loop会在非loop线程内不会死循环，在loop线程内死循环，而多进程模式也不好计算privdata->loops内部私有数组实际数量，不同线程环境行为不一致和idx语义有歧义所以调整了超出idx最大范围时返回NULL
=> fix HttpServer::loop idx iteration exception

cpputil/hstring.cpp, cpputil/hstring.h, http/server/HttpHandler.cpp, http/server/HttpHandler.h
因为这个内部的大文件处理是采用的HFile封装的标准库ANSI函数处理，而通常只有Windows环境的ANSI不是UTF8编码，所以为了改动幅度最小化并且避免引入iconv外部第三方编码转换库只好借助内置的窄宽字符转换先将浏览器请求的UTF8字符串转换到宽字符，在从宽字符转换到对应本地化编码的ANSI，虽然存在两次转换但大文件传输并不高频触发且系统内置编码转换效率极高影响不大，也为了方便后续Windows环境有这方面转换需要都整合到hstring.h中了。
=> 修复 defaultLargeFileHandler 在Windows环境不支持中文

event/hevent.c, event/nio.c, http/HttpMessage.cpp, http/HttpParser.cpp, http/server/HttpHandler.cpp, ssl/openssl.c
主要优化某些日志等级不合适且内容完全一样不易区分还没有携带较重要的参数信息，以及ssl握手错误太含糊所以补充了openssl具体错误原因，还有些与Server请求处理强相关的fprintf(stderr)输出的错误会因外部高频恶意请求造成频繁输出在shell便调整到hlog日志模块记录了。
=> 优化部分日志级别和消息描述

base/hmain.c, base/hmain.h
因为signal_handle内部自动exit结束程序，而当业务层需要在exit之前做一些操作(例如执行打开正在运行的http服务首页url)，因此需要支持一个不自动exit的函数版本。
因为不是所有程序都是控制台程序，而非控制台程序需要采用MessageBox或其他信息渲染方式来提示信息，因此需要支持自定义设置hmain使用的printf函数指针接管后由用户业务层采用其他形式进行提示。
=> 支持hmain兼容windows非控制台以及linux gui程序

base/hsocket.c, base/hsocket.h, event/rudp.c
使用memcmp直接比较两个sockaddr可能出现结果不符合预期的情况，如下两个sockaddr结构：
其协议、ip和端口是相同的，但sin_zero填充部分不一致，导致memcmp返回值不符合预期。
由于结果不正确，导致`rudp_get`函数意外创建了新的`rudp_entry_t`，kcp因此也受到影响，无法正常收包。
`hio_read_kcp`->`hio_get_kcp`->`hio_get_rudp`->`rudp_get`
=> 修复sockaddr比较结果不符合预期导致kcp无法正常收包问题

event/hevent.h, event/hloop.c
This PR addresses [issue #754](https://github.com/ithewei/libhv/issues/754) — a rare race condition involving multithreading and socket reuse when using `hio_detach` / `hio_attach`.
> Note: The patch was implemented by @ithewei based on the issue I reported. I'm submitting this PR just to help close the loop and track the fix properly.
Thanks again for the fix and for maintaining the project!
=> Prevent race condition when detaching sockets
